"""`AutoGenAdapter`: AgentMesh instrumentation for classic/AG2-style AutoGen
conversational multi-agent chats.

Package note (see `LIMITATIONS.md` for the full writeup): "AutoGen" on PyPI
has had several name transitions. In this adapter's development sandbox,
`pip install pyautogen` resolved to a near-empty 0.10.0 compatibility-shim
release with no `ConversableAgent`/`GroupChat` surface at all, while
`pip install ag2` resolved to 0.14.0, which provides the classic, stable
`import autogen` namespace (`ConversableAgent`, `GroupChat`,
`GroupChatManager`, `register_reply`, `execute_function`, `hook_lists`)
that `docs/plan/Architecture.md` §3's mapping table and this milestone's
plan describe. This adapter is built and exercised against `ag2` (the
`autogen` distribution actively maintained by the original AutoGen team
after Microsoft's fork became the separate, differently-shaped
`autogen-agentchat` package — that newer package's `AssistantAgent`/
`RoundRobinGroupChat` async API is *not* what this adapter targets).

Mapping (`docs/plan/Architecture.md` §3's AutoGen row)
-------------------------------------------------------
    agent message generation       -> llm.call
    function/tool call in message  -> tool.call
    message routed to a different agent in the group chat -> agent.handoff

AutoGen has no single "message-passing" hook that already carries this
distinction, so this adapter wires three separate, narrower hook points
instead of one broad callback (see `LIMITATIONS.md` for hooks this
deliberately does *not* use, e.g. `register_hook`'s `hook_lists`):

1. `ConversableAgent.execute_function` -- the one place AutoGen actually
   *runs* a registered function/tool for a `function_call`/`tool_calls`
   entry, regardless of which higher-level reply function triggered it.
   Wrapped per-instance: every call brackets exactly one `tool.call` span.
2. `ConversableAgent.generate_reply` -- AutoGen's single reply-dispatch
   entrypoint (covers real LLM inference, canned/scripted replies, and
   auto function-execution replies alike -- AutoGen does not distinguish
   these at the API boundary). Wrapped per-instance as a structural
   (`kind=None`) span so nested `execute_function` calls resolve their
   parent correctly, then classified once the real call returns:
     - a reply whose `role` is `"function"`/`"tool"` is a raw tool-result
       message auto-generated by `generate_function_call_reply`/
       `generate_tool_calls_reply` (which themselves call
       `execute_function` -- already captured in step 1). Exporting this
       too would double-count one tool invocation as both a `tool.call`
       and an `llm.call`, so it is intentionally *not* exported.
     - anything else (plain text, or a dict proposing a
       `function_call`/`tool_calls`) is genuine "agent message
       generation" -> exported as `llm.call`.
3. `GroupChat.select_speaker` -- the exact moment AutoGen decides which
   agent a message is routed to next. Wrapped per-instance: every call
   brackets one `agent.handoff` span, opened *before* the newly-selected
   agent's `generate_reply` runs and closed once it returns, so whatever
   that agent produces nests underneath its own handoff -- e.g. a
   reviewer agent's `llm.call` becomes a child of the `agent.handoff` that
   routed to it. This assumes stock `GroupChatManager.run_chat`'s
   contract that a `select_speaker` call is immediately followed by
   exactly one `generate_reply` call on the newly selected speaker (see
   `LIMITATIONS.md` for what happens if that assumption doesn't hold).

Everything else AutoGen fires (message broadcasts to non-speaking
participants, `GroupChatManager`'s own bookkeeping, `process_*` hooks) is
either left completely untouched or, where it would otherwise break
parent-chain linkage, tracked via `kind=None` structural entries that are
never exported (`agentmesh_integrations_common.context.SpanTracker`).
"""

from __future__ import annotations

import json
import logging
import uuid
from typing import Any, Optional

from autogen import ConversableAgent, GroupChat, GroupChatManager

from agentmesh_integrations_common.adapter import FrameworkAdapter
from agentmesh_integrations_common.spans import FRAMEWORK_ATTR, SpanKind, SpanStatus

logger = logging.getLogger("agentmesh_autogen")

__all__ = ["AutoGenAdapter"]

# `generate_reply()` return values carrying one of these `role`s are raw
# function/tool execution results auto-generated by
# `generate_function_call_reply`/`generate_tool_calls_reply`, not new LLM
# content -- see the module docstring's point 2.
_TOOL_RESULT_ROLES = frozenset({"function", "tool"})


def _reply_output_text(reply: Any) -> str:
    """Best-effort stringification of a `generate_reply()` return value for
    a span's `output` field."""
    if reply is None:
        return ""
    if isinstance(reply, str):
        return reply
    if isinstance(reply, dict):
        content = reply.get("content")
        if content is not None:
            return content if isinstance(content, str) else json.dumps(content, default=str)
        return json.dumps(reply, default=str)
    return str(reply)


def _is_llm_generation(reply: Any) -> bool:
    """Classify a `generate_reply()` return value per the module
    docstring's point 2: `True` means "export this as `llm.call`"."""
    if reply is None:
        return False
    if isinstance(reply, dict) and reply.get("role") in _TOOL_RESULT_ROLES:
        return False
    return True


def _agent_name(agent: Any) -> str:
    return getattr(agent, "name", str(agent))


class AutoGenAdapter(FrameworkAdapter):
    """Instruments an AutoGen `GroupChat`/`GroupChatManager` to emit
    AgentMesh spans for its conversation.

    One `AutoGenAdapter` instance is meant to instrument one logical
    conversation. It opens a single persistent structural (`kind=None`)
    root span in `__init__` so that *every* event this adapter later
    tracks -- however many separate top-level AutoGen calls produce them
    (a direct `agent.generate_reply()` call, a later `initiate_chat()`,
    ...) -- resolves to the same `trace_id`, per Milestone 3's
    "no orphan spans" / "single trace" test-strategy requirements. See
    `LIMITATIONS.md` for why this root is intentionally never `finish()`-ed
    and what that implies for reusing one adapter across conversations.
    """

    def __init__(self, tracer) -> None:
        super().__init__(tracer)
        self._root_external_id = f"autogen-root:{uuid.uuid4().hex}"
        self.spans.start(self._root_external_id, None, "autogen.conversation")
        self._parent_stack: list[str] = [self._root_external_id]
        self._pending_handoff_external_id: Optional[str] = None

    def instrument(self, target: Any) -> None:
        """Wire this adapter onto an AutoGen `GroupChat` or
        `GroupChatManager`. Safe to call once per `target`; a second call
        on an already-instrumented `GroupChat`/agent is a no-op.
        """
        if isinstance(target, GroupChatManager):
            groupchat = target.groupchat
        elif isinstance(target, GroupChat):
            groupchat = target
        else:
            raise TypeError(
                "AutoGenAdapter.instrument() expects an autogen GroupChat or "
                f"GroupChatManager, got {type(target)!r}"
            )

        if getattr(groupchat, "_agentmesh_instrumented", False):
            return
        groupchat._agentmesh_instrumented = True

        self._wrap_select_speaker(groupchat)
        for agent in groupchat.agents:
            self._instrument_agent(agent)
        # `GroupChatManager` itself is intentionally not instrumented for
        # generate_reply/execute_function: in stock `run_chat`, the manager
        # only orchestrates -- it never independently generates
        # conversational content or executes a function as a participant
        # (see `LIMITATIONS.md`).

    # -- per-agent hooks ---------------------------------------------------

    def _instrument_agent(self, agent: ConversableAgent) -> None:
        if getattr(agent, "_agentmesh_instrumented", False):
            return
        agent._agentmesh_instrumented = True
        self._wrap_generate_reply(agent)
        self._wrap_execute_function(agent)

    def _wrap_execute_function(self, agent: ConversableAgent) -> None:
        original = agent.execute_function

        def wrapped(func_call, call_id=None, verbose=False, _original=original, _agent=agent):
            func_name = func_call.get("name", "unknown-function")
            external_id = f"tool:{uuid.uuid4().hex}"
            parent = self._parent_stack[-1] if self._parent_stack else None
            self.spans.start(
                external_id,
                SpanKind.TOOL_CALL,
                func_name,
                parent_external_id=parent,
                attributes={
                    FRAMEWORK_ATTR: "autogen",
                    "autogen.agent": _agent_name(_agent),
                    "autogen.function_arguments": func_call.get("arguments", ""),
                },
            )
            try:
                is_success, result = _original(func_call, call_id=call_id, verbose=verbose)
            except Exception as exc:
                self.spans.finish(external_id, status=SpanStatus.ERROR, output=str(exc))
                raise
            output = result.get("content") if isinstance(result, dict) else result
            self.spans.finish(
                external_id,
                status=SpanStatus.OK if is_success else SpanStatus.ERROR,
                output=output if isinstance(output, str) else json.dumps(output, default=str),
            )
            return is_success, result

        agent.execute_function = wrapped

    def _wrap_generate_reply(self, agent: ConversableAgent) -> None:
        original = agent.generate_reply

        def wrapped(messages=None, sender=None, exclude=(), _original=original, _agent=agent):
            struct_id = f"turn:{uuid.uuid4().hex}"
            parent = self._parent_stack[-1] if self._parent_stack else None
            self.spans.start(struct_id, None, f"{_agent_name(_agent)}.generate_reply", parent_external_id=parent)
            self._parent_stack.append(struct_id)

            reply: Any = None
            error: Optional[BaseException] = None
            try:
                reply = _original(messages=messages, sender=sender, exclude=exclude)
            except BaseException as exc:  # noqa: BLE001 - re-raised below
                error = exc
            finally:
                if self._parent_stack and self._parent_stack[-1] == struct_id:
                    self._parent_stack.pop()

            if error is not None:
                self.spans.finish(struct_id, status=SpanStatus.ERROR, output=str(error))
                self._close_pending_handoff(output=str(error), status=SpanStatus.ERROR)
                raise error

            if _is_llm_generation(reply):
                llm_id = f"llm:{uuid.uuid4().hex}"
                self.spans.start(
                    llm_id,
                    SpanKind.LLM_CALL,
                    f"{_agent_name(_agent)}.generate_reply",
                    parent_external_id=struct_id,
                    attributes={
                        FRAMEWORK_ATTR: "autogen",
                        "autogen.agent": _agent_name(_agent),
                        "autogen.sender": _agent_name(sender) if sender is not None else None,
                    },
                )
                self.spans.finish(llm_id, output=_reply_output_text(reply))

            self.spans.finish(struct_id)
            self._close_pending_handoff(output=_reply_output_text(reply), status=SpanStatus.OK)
            return reply

        agent.generate_reply = wrapped

    # -- group-chat-level hook ----------------------------------------------

    def _wrap_select_speaker(self, groupchat: GroupChat) -> None:
        original = groupchat.select_speaker

        def wrapped(last_speaker, selector, _original=original):
            new_speaker = _original(last_speaker, selector)

            if self._pending_handoff_external_id is not None:
                # A previous handoff was never closed by a following
                # generate_reply call (e.g. a custom `run_chat` override
                # called select_speaker twice back-to-back) -- close it
                # defensively rather than leak an open span forever.
                self._close_pending_handoff(output=None, status=SpanStatus.ERROR)

            external_id = f"handoff:{uuid.uuid4().hex}"
            parent = self._parent_stack[-1] if self._parent_stack else None
            self.spans.start(
                external_id,
                SpanKind.AGENT_HANDOFF,
                f"{_agent_name(last_speaker)} -> {_agent_name(new_speaker)}",
                parent_external_id=parent,
                attributes={
                    FRAMEWORK_ATTR: "autogen",
                    "autogen.from_agent": _agent_name(last_speaker),
                    "autogen.to_agent": _agent_name(new_speaker),
                },
            )
            # Left open on purpose: `GroupChatManager.run_chat` calls
            # `new_speaker.generate_reply(...)` immediately after this
            # returns, and our `generate_reply` wrapper is what closes this
            # handoff (see `_close_pending_handoff`) once that call
            # completes, so the new speaker's own spans nest under it.
            self._pending_handoff_external_id = external_id
            self._parent_stack.append(external_id)
            return new_speaker

        groupchat.select_speaker = wrapped

    # -- shared bookkeeping ---------------------------------------------------

    def _close_pending_handoff(self, *, output: Optional[str], status: SpanStatus) -> None:
        handoff_id = self._pending_handoff_external_id
        if handoff_id is None:
            return
        self._pending_handoff_external_id = None
        self.spans.finish(handoff_id, status=status, output=output)
        if self._parent_stack and self._parent_stack[-1] == handoff_id:
            self._parent_stack.pop()
